steps:

- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './src']

- id: "Image Build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'desafioci', '.']

images:
  - 'gcr.io/$PROJECT_ID/aguinelo:latest'
