steps:

- id: "Rodando app test"
  name: 'gcr.io/cloud-builders/go'
  args: ['go', 'test']

- id: "Image Build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['docker', 'build', '-t', 'desafioci', '.']
